name: birdle
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/ellipse/

  fonts:
    - family: GrandHotel
      fonts:
        - asset: assets/fonts/GrandHotel-Regular.ttf
          weight: 400

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
